/**
 * Invitation Service — handles bulk CSV importing of shortlisted teams.
 *
 * @module server/services/invitation.service
 */

import { FieldValue } from 'firebase-admin/firestore';
import { getAdminDb } from '@/lib/firebase-admin';
import { writeAuditLog } from './audit.service';
import type { UserRole } from '@/types/auth';
import { sendEmail } from './email.service';
import { env } from '@/lib/env';

export interface CsvRow {
  teamName: string;
  leaderName: string;
  leaderEmail: string;
  leaderPhone: string;
  college: string;
}

export interface ImportResult {
  imported: number;
  skipped: number;
  failed: number;
}

/**
 * Imports a batch of shortlisted teams from parsed CSV data.
 * Skips duplicates based on leaderEmail.
 * Uses chunked batched writes (max 500 per batch in Firestore, we use 50 for safety).
 */
export async function importInvitations(
  records: CsvRow[],
  actorUid: string,
  actorRole: UserRole,
  batchId: string, // UUID generated by the router to tag this import session
): Promise<ImportResult> {
  const db = getAdminDb();
  
  const result: ImportResult = {
    imported: 0,
    skipped: 0,
    failed: 0,
  };

  // 1. Fetch all existing emails to handle deduplication in-memory efficiently
  const existingDocs = await db.collection('invitedTeams').select('leaderEmail').get();
  const existingEmails = new Set(
    existingDocs.docs.map(doc => doc.data()['leaderEmail'].toLowerCase())
  );

  // 2. Filter out duplicates from the incoming records
  const validRecords: CsvRow[] = [];
  
  for (const record of records) {
    if (!record.leaderEmail) {
      result.failed++;
      continue;
    }

    const email = record.leaderEmail.toLowerCase().trim();
    if (existingEmails.has(email)) {
      result.skipped++;
      continue;
    }

    // Add to valid records and local set to prevent duplicates within the CSV itself
    validRecords.push(record);
    existingEmails.add(email);
  }

  if (validRecords.length === 0) {
    return result;
  }

  // 3. Chunk into batches of 50
  const CHUNK_SIZE = 50;
  for (let i = 0; i < validRecords.length; i += CHUNK_SIZE) {
    const chunk = validRecords.slice(i, i + CHUNK_SIZE);
    const batch = db.batch();

    for (const record of chunk) {
      const docRef = db.collection('invitedTeams').doc(); // Auto-generate ID
      batch.set(docRef, {
        teamName: record.teamName.trim(),
        leaderName: record.leaderName.trim(),
        leaderEmail: record.leaderEmail.toLowerCase().trim(),
        leaderPhone: record.leaderPhone.trim(),
        college: record.college.trim(),
        status: 'Invited', // Initial state
        importBatchId: batchId,
        importedAt: FieldValue.serverTimestamp(),
      });
    }

    // Commit the batch
    try {
      await batch.commit();
      result.imported += chunk.length;
      
      // Phase 11: Fire off invitation emails asynchronously
      const loginUrl = env.NEXT_PUBLIC_APP_URL ? `${env.NEXT_PUBLIC_APP_URL}/login` : 'https://revengershack.com/login';
      Promise.allSettled(chunk.map(record => 
        sendEmail({
            to: record.leaderEmail.toLowerCase().trim(),
            template: 'invitation',
            variables: { teamName: record.teamName, loginUrl }
        })
      )).catch(e => console.error("Error triggering invitation emails", e));
      
    } catch (err) {
      console.error(`Failed to commit batch during CSV import`, err);
      // If a batch fails, we count all of its items as failed
      result.failed += chunk.length;
    }
  }

  // 4. Write audit log
  await writeAuditLog({
    action: 'team.invitation_imported',
    actorUid,
    actorRole,
    targetId: batchId,
    targetType: 'invitedTeams',
    metadata: {
      totalProvided: records.length,
      imported: result.imported,
      skipped: result.skipped,
      failed: result.failed,
    },
    ip: null,
  });

  return result;
}
